### PR TITLE
fix activities display for merge and split events after refactoring

### LINKED ISSUE #148: Merge event missing merge_from gene ID
Prior to the refactor, the event in recent activities would include gene/id of merged_from gene. It's no longer happening now. Not sure if this is by design.

### PR DESCRIPTION
**Pull request by sibyl229**
fixes #148 

Can I assume the changes on the "split into gene" will include the following? (I can't test this yet, due to #153)
```
{ attr: 'gene/status', value: 'gene.status/live', added: 'true' }
```

### CODE REVIEW

**Comment by mgrbyte** [comment]
@sibyl229 
> Can I assume the changes on the "split into gene" will include the following? (I can't test this yet, due to #153)

:+1:

File: client/src/containers/Gene/GeneActivitiesTable.js [hunk 1]
```diff
@@ -78,49 +78,66 @@ class GeneActivitiesTable extends Component {
...
-      'gene/id': selfGeneId,
-    };
-    const [entityKey] = entityKeys.filter(
-      (key) => activityItem[key] && activityItem[key]['gene/id'] === selfGeneId
-    );
-    const [relatedEntityKey] = entityKeys.filter(
-      (key) => activityItem[key] && activityItem[key]['gene/id'] !== selfGeneId
+  getActivityDescriptor = (activityItem = {}, selfGeneId) => {
+    const what = activityItem['provenance/what'];
+    const { statusChange, relatedGeneId } = (activityItem.changes || []).reduce(
```
Comment (mgrbyte) [inline client/src/containers/Gene/GeneActivitiesTable.js:83]:
```suggestion
    const { statusChange, relatedGeneId } = (activityItem.changes || []).reduce(
    if (added)
      if (attr == 'gene/splits' || attr == 'gene/merges') {
         return {
            ...result,
            relatedGeneId: value,
         };
      } else if (attr == 'gene/status') {
        return {
          ..result,
          statusChange: value,
        };
     } 
    return {
          ...result
    }
```

File: client/src/containers/Gene/GeneActivitiesTable.js [hunk 2]
```diff
@@ -78,49 +78,66 @@ class GeneActivitiesTable extends Component {
...
-        activityItem['provenance/split-into'] === activityItem[entityKey]
-      ) {
-        eventType = 'split_from';
-      } else if (
-        activityItem['provenance/split-from'] === activityItem[entityKey]
-      ) {
-        eventType = 'split_into';
-      }
+    if (what === 'event/merge-genes' && !statusChange) {
+      eventType = 'merge_from';
```
Comment (mgrbyte) [inline client/src/containers/Gene/GeneActivitiesTable.js:105]:
```suggestion
      eventType = 'merged_from';
```

File: client/src/containers/Gene/GeneActivitiesTable.js [hunk 3]
```diff
@@ -78,49 +78,66 @@ class GeneActivitiesTable extends Component {
...
+    } else if (
+      what === 'event/merge-genes' &&
+      statusChange === 'gene.status/dead'
+    ) {
+      eventType = 'merge_into';
```
Comment (mgrbyte) [inline client/src/containers/Gene/GeneActivitiesTable.js:110]:
```suggestion
      eventType = 'merged_into';
```

**Review by mgrbyte — COMMENTED** [review]
I've left some suggestions inline, generally :+1:

File: client/src/containers/Gene/GeneActivitiesTable.js (hunk 3 above)
Comment (sibyl229) [reply client/src/containers/Gene/GeneActivitiesTable.js:110]: I have never seen inline suggestion in action before. It's really nice.

I would prefer to leave "merge_into" and "merge_from" in present tense, because: 
- it's more consistent with values returned by provenance/what 
- (more of a personal taste) I'm okay with reading log entries in present tense, as I interpret it as being written when things are happening. But I don't know if others might find it confusing.

That being said, if past tense is preferred here, we would need a mapping (to past tense) for all the values returned by provenance/what.

Comment (mgrbyte) [reply client/src/containers/Gene/GeneActivitiesTable.js:110]: @sibyl229  hehe, I prefer past tense (because it has happened) - was/is certainly the intention.

`provenance` should only contain past/neutral-tense keys (full list):
 `when`
 `what`
 `who`
 `why` 

`grep provenance resources/schema/*edn`

n.b provenance keys merged-into merged-from, split-from, split-into have been deprecated (not used by the app). 

I don't mind if you want use present tense :smile:

Comment (mgrbyte) [reply client/src/containers/Gene/GeneActivitiesTable.js:110]: @sibyl229 except my JS suggestions contained invalid syntax :weary:

**Comment by sibyl229** [comment]
@mgrbyte ah, I should have checked the syntax. Should be fixed now. 

For the past tense enhancement. I created a separate issue for myself. #155 Maybe are right. It seems to read better in past tense. But please let me think about this a bit more, especially whether the history should behave like a table (like the overall history table that we would eventually build that allows filtering) or a list.

**Comment by mgrbyte** [comment]
@sibyl229  - wondering if this should be merged in?

**Comment by sibyl229** [comment]
@mgrbyte please feel free to merge. I will fix the wording in a separate PR.
